[project]
name = "pox-clarinet-tests"
requirements = []

[contracts.pox-mainnet]
path = "contracts/pox-mainnet.clar"
clarity_version = 2
epoch = "2.1"

[contracts.pox-3]
path = "contracts/pox-3.clar"
clarity_version = 2
epoch = "2.1"

[contracts.builtin]
path = "contracts/builtin.clar"
clarity_version = 2
epoch = "2.1"

[contracts.intermediary]
path = "contracts/intermediary.clar"
clarity_version = 2
epoch = "2.1"
